### ISSUE TITLE
直接复制粘贴不能叫做参考

### ISSUE THREAD

**Issue by Snailclimb** [danmuking/all-in-one#1]
你是不是不懂参考是什么意思？复制我的内容过来有意义吗？我想问问。图片用我的，内容用我的，真有你的。另外，我的内容已经申请软件著作权，是可以寻求法律帮助的。

<img width="1362" alt="image" src="https://github.com/danmuking/all-in-one/assets/29880145/9aaa0e5c-7f98-4108-a59f-2c4822172174">

**Comment by danmuking** [comment]
已删除相关转载内容
